name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_cache:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_cargo
      - name: build
        run: cargo build --release --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - uses: ./.github/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: ./.github/actions/cache_cargo
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: test
      run: cargo test --release --verbose

  minrt_mini:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: create minrt_mini ppm
      run: ulimit -s unlimited && cargo run --release -- --bin minrt_mini.bin
    
    - name: upload minrt_mini ppm
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: ./minrt_mini.ppm
